count articles in FAQ subcategories for explorer view
znuny/FAQ pull request #2
Opened 2021-06-07 07:43 UTC by reneeb

Currently visitors of the FAQ explorer might see the article count 0 if articles only exist
in subcategories. This might people make think that no articles exist at all. And additionally
the ticket overview by queue works differently.

To keep backwards compatibility the new behaviour has to be switched on in the sysconfig.

2021-08-10 17:26 UTC, rkaldung commented
@reneeb Really like this.

2021-08-10 17:27 UTC, rkaldung commented
@jepf Do you think we can this push into the upcoming version too? If not let's keep it for the next round.

2021-08-11 12:25 UTC, jepf requested changes

2021-08-11 12:25 UTC, jepf commented on Kernel/Config/Files/XML/FAQ.xml
> +        <Description Translatable="1">Count articles from FAQ subcategories for explorer.</Description>
```suggestion
        <Description Translatable="1">Enable counting of articles from FAQ sub-categories for FAQ explorer.</Description>
```

Could you please add the German translation for the description to de_FAQ.pm?

2021-08-11 12:25 UTC, jepf commented on Kernel/System/FAQ.pm
> +
```suggestion
    my $ConfigObject = $Kernel::OM->Get('Kernel::Config');
    
    my $CountSubCategories = $ConfigObject->Get('FAQExplorer::CountSubCategories');
    if ( $Param{CountSubCategories} && $CountSubCategories ) {
        my %Categories;

        my $CategoryList = $Self->CategoryList(
            UserID => $Param{UserID},
        );

        my @CategoryIDs = @{ $Param{CategoryIDs} || [] };
        CATEGORYID:
        while ( my $CategoryID = shift @CategoryIDs ) {
            $Categories{$CategoryID}++;

            next CATEGORYID if !exists $CategoryList->{$CategoryID};

            push @CategoryIDs, keys %{ $CategoryList->{$CategoryID} };
        }

        $Param{CategoryIDs} = [
            keys %Categories,
        ];
    }
```

Could you please add a small unit test for this?

2023-06-02 11:19 UTC, NiklasSchmitt approved these changes

2023-06-02 11:30 UTC, merged